// Code generated by generate_getters.go; DO NOT EDIT.
package examples

// Getter methods generated from default tags and zero values.

// ======= Getter methods for Live =======
func (r *Live) GetLiveNameOrDefault(defaultValue string) string {
	if r.LiveName != nil {
		return *r.LiveName
	}
	return defaultValue
}

func (r *Live) GetStatusOrDefault(defaultValue StatusType) StatusType {
	if r.Status != nil {
		return *r.Status
	}
	return defaultValue
}

func (r *Live) GetLiveTypeOrDefault(defaultValue int64) int64 {
	if r.LiveType != nil {
		return *r.LiveType
	}
	return defaultValue
}

func (r *Live) GetIsSpecialOrDefault(defaultValue bool) bool {
	if r.IsSpecial != nil {
		return *r.IsSpecial
	}
	return defaultValue
}

func (r *Live) GetIsAvailableOrDefault(defaultValue bool) bool {
	if r.IsAvailable != nil {
		return *r.IsAvailable
	}
	return defaultValue
}

func (r *Live) GetRateOrDefault(defaultValue float64) float64 {
	if r.Rate != nil {
		return *r.Rate
	}
	return defaultValue
}

func (r *Live) GetDefaultRateOrDefault(defaultValue float64) float64 {
	if r.DefaultRate != nil {
		return *r.DefaultRate
	}
	return defaultValue
}

// ======= Getter methods for LiveAliased =======
func (r *LiveAliased) GetLiveNameOrDefault(defaultValue string) string {
	if r.LiveName != nil {
		return *r.LiveName
	}
	return defaultValue
}

func (r *LiveAliased) GetStatusOrDefault(defaultValue StatusType) StatusType {
	if r.Status != nil {
		return *r.Status
	}
	return defaultValue
}

func (r *LiveAliased) GetLiveTypeOrDefault(defaultValue int64) int64 {
	if r.LiveType != nil {
		return *r.LiveType
	}
	return defaultValue
}

func (r *LiveAliased) GetIsSpecialOrDefault(defaultValue bool) bool {
	if r.IsSpecial != nil {
		return *r.IsSpecial
	}
	return defaultValue
}

func (r *LiveAliased) GetIsAvailableOrDefault(defaultValue bool) bool {
	if r.IsAvailable != nil {
		return *r.IsAvailable
	}
	return defaultValue
}

func (r *LiveAliased) GetRateOrDefault(defaultValue float64) float64 {
	if r.Rate != nil {
		return *r.Rate
	}
	return defaultValue
}

func (r *LiveAliased) GetDefaultRateOrDefault(defaultValue float64) float64 {
	if r.DefaultRate != nil {
		return *r.DefaultRate
	}
	return defaultValue
}

