// Code generated by generate_getters.go; DO NOT EDIT.
package examples

// Getter methods generated from default tags and zero values.

// ======= Getter methods for Live =======
func (r *Live) GetLiveName() string {
	if r.LiveName != nil {
		return *r.LiveName
	}
	return ""
}

func (r *Live) GetStatus() string {
	if r.Status != nil {
		return *r.Status
	}
	return "preparing"
}

func (r *Live) GetLiveType() int64 {
	if r.LiveType != nil {
		return *r.LiveType
	}
	return 0
}

func (r *Live) GetIsSpecial() bool {
	if r.IsSpecial != nil {
		return *r.IsSpecial
	}
	return false
}

func (r *Live) GetIsAvailable() bool {
	if r.IsAvailable != nil {
		return *r.IsAvailable
	}
	return true
}

func (r *Live) GetRate() float64 {
	if r.Rate != nil {
		return *r.Rate
	}
	return 0
}

func (r *Live) GetDefaultRate() float64 {
	if r.DefaultRate != nil {
		return *r.DefaultRate
	}
	return 3.5
}

// ======= Getter methods for LiveAliased =======
func (r *LiveAliased) GetLiveName() string {
	if r.LiveName != nil {
		return *r.LiveName
	}
	return ""
}

func (r *LiveAliased) GetStatus() string {
	if r.Status != nil {
		return *r.Status
	}
	return "preparing"
}

func (r *LiveAliased) GetLiveType() int64 {
	if r.LiveType != nil {
		return *r.LiveType
	}
	return 0
}

func (r *LiveAliased) GetIsSpecial() bool {
	if r.IsSpecial != nil {
		return *r.IsSpecial
	}
	return false
}

func (r *LiveAliased) GetIsAvailable() bool {
	if r.IsAvailable != nil {
		return *r.IsAvailable
	}
	return true
}

func (r *LiveAliased) GetRate() float64 {
	if r.Rate != nil {
		return *r.Rate
	}
	return 0
}

func (r *LiveAliased) GetDefaultRate() float64 {
	if r.DefaultRate != nil {
		return *r.DefaultRate
	}
	return 3.5
}
